/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prototipo1.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author anaso
 */
public class GUIPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuAdicionarEmpresa = new javax.swing.JMenuItem();
        menuBuscarEmpresa = new javax.swing.JMenuItem();
        menuActualizarEmpresa = new javax.swing.JMenuItem();
        menuEliminarEmpresa = new javax.swing.JMenuItem();
        menuListarEmpresa = new javax.swing.JMenuItem();
        menuSumatoriaEmpresa = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuAdicionarEmpleado = new javax.swing.JMenuItem();
        menuBuscarEmpleado = new javax.swing.JMenuItem();
        menuActualizarEmpleado = new javax.swing.JMenuItem();
        menuElimiarEmpresa = new javax.swing.JMenuItem();
        menuListarEmpleados = new javax.swing.JMenuItem();
        menuSumatoriaEmpleado = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuDesarrolladores = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Principal");

        jMenu2.setText("Inicio");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Empresa");

        menuAdicionarEmpresa.setText("Adicionar Empresa");
        menuAdicionarEmpresa.addActionListener(this::menuAdicionarEmpresaActionPerformed);
        jMenu3.add(menuAdicionarEmpresa);

        menuBuscarEmpresa.setText("Buscar Empresa");
        menuBuscarEmpresa.addActionListener(this::menuBuscarEmpresaActionPerformed);
        jMenu3.add(menuBuscarEmpresa);

        menuActualizarEmpresa.setText("ActualizarEmpresa");
        menuActualizarEmpresa.addActionListener(this::menuActualizarEmpresaActionPerformed);
        jMenu3.add(menuActualizarEmpresa);

        menuEliminarEmpresa.setText("Eliminar Empresa");
        menuEliminarEmpresa.addActionListener(this::menuEliminarEmpresaActionPerformed);
        jMenu3.add(menuEliminarEmpresa);

        menuListarEmpresa.setText("Listar Empresa");
        menuListarEmpresa.addActionListener(this::menuListarEmpresaActionPerformed);
        jMenu3.add(menuListarEmpresa);

        menuSumatoriaEmpresa.setText("Sumatoria");
        menuSumatoriaEmpresa.addActionListener(this::menuSumatoriaEmpresaActionPerformed);
        jMenu3.add(menuSumatoriaEmpresa);

        jMenuBar1.add(jMenu3);

        jMenu7.setText("Empleado");

        menuAdicionarEmpleado.setText("Adicionar Empleado");
        menuAdicionarEmpleado.addActionListener(this::menuAdicionarEmpleadoActionPerformed);
        jMenu7.add(menuAdicionarEmpleado);

        menuBuscarEmpleado.setText("Buscar Empleado");
        menuBuscarEmpleado.addActionListener(this::menuBuscarEmpleadoActionPerformed);
        jMenu7.add(menuBuscarEmpleado);

        menuActualizarEmpleado.setText("Actualizar Empleado");
        menuActualizarEmpleado.addActionListener(this::menuActualizarEmpleadoActionPerformed);
        jMenu7.add(menuActualizarEmpleado);

        menuElimiarEmpresa.setText("Eliminar  Empleado");
        menuElimiarEmpresa.addActionListener(this::menuElimiarEmpresaActionPerformed);
        jMenu7.add(menuElimiarEmpresa);

        menuListarEmpleados.setText("Listar Empleados");
        menuListarEmpleados.addActionListener(this::menuListarEmpleadosActionPerformed);
        jMenu7.add(menuListarEmpleados);

        menuSumatoriaEmpleado.setText("Sumatoria");
        menuSumatoriaEmpleado.addActionListener(this::menuSumatoriaEmpleadoActionPerformed);
        jMenu7.add(menuSumatoriaEmpleado);

        jMenuBar1.add(jMenu7);

        jMenu4.setText("Acerca de");

        menuDesarrolladores.setText("Desarrolladores");
        menuDesarrolladores.addActionListener(this::menuDesarrolladoresActionPerformed);
        jMenu4.add(menuDesarrolladores);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDesarrolladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDesarrolladoresActionPerformed
        String mensaje = "Desarrolladores: \n\n" + 
                "Paula Daniela Cubillos \n" +
                "Michael Stiven Castaño \n" +
                "Ana Sofia Vergara \n";
        JOptionPane.showInternalMessageDialog(null, mensaje);
    }//GEN-LAST:event_menuDesarrolladoresActionPerformed

    private void menuAdicionarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdicionarEmpresaActionPerformed
        GUIAdicionarEmpresa gui = new GUIAdicionarEmpresa();
        gui.setVisible(true);
    }//GEN-LAST:event_menuAdicionarEmpresaActionPerformed

    private void menuBuscarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarEmpresaActionPerformed
        GUIBuscarEmpresa gui = new GUIBuscarEmpresa();
        gui.setVisible(true);
    }//GEN-LAST:event_menuBuscarEmpresaActionPerformed

    private void menuActualizarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizarEmpresaActionPerformed
        GUIActualizarEmpresa gui = new GUIActualizarEmpresa();
        gui.setVisible(true);
    }//GEN-LAST:event_menuActualizarEmpresaActionPerformed

    private void menuEliminarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarEmpresaActionPerformed
        GUIEliminarEmpresa gui = new GUIEliminarEmpresa();
        gui.setVisible(true);
    }//GEN-LAST:event_menuEliminarEmpresaActionPerformed

    private void menuListarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarEmpresaActionPerformed
        GUIListarEmpresas gui = new GUIListarEmpresas();
        gui.setVisible(true);
    }//GEN-LAST:event_menuListarEmpresaActionPerformed

    private void menuSumatoriaEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSumatoriaEmpresaActionPerformed
        GUISumatoriaIngresos gui = new GUISumatoriaIngresos();
        gui.setVisible(true);
    }//GEN-LAST:event_menuSumatoriaEmpresaActionPerformed

    private void menuBuscarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarEmpleadoActionPerformed
        GUIBuscarEmpleado gui = new GUIBuscarEmpleado();
        gui.setVisible(true);
    }//GEN-LAST:event_menuBuscarEmpleadoActionPerformed

    private void menuAdicionarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdicionarEmpleadoActionPerformed
        GUIAdicionarEmpleado gui = new GUIAdicionarEmpleado();
        gui.setVisible(true);
    }//GEN-LAST:event_menuAdicionarEmpleadoActionPerformed

    private void menuActualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizarEmpleadoActionPerformed
        GUIActualizarEmpleado gui = new GUIActualizarEmpleado();
        gui.setVisible(true);
    }//GEN-LAST:event_menuActualizarEmpleadoActionPerformed

    private void menuElimiarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuElimiarEmpresaActionPerformed
        GUIEliminarEmpleado gui = new GUIEliminarEmpleado();
        gui.setVisible(true);
    }//GEN-LAST:event_menuElimiarEmpresaActionPerformed

    private void menuListarEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarEmpleadosActionPerformed
        GUIListarEmpleados gui = new GUIListarEmpleados();
        gui.setVisible(true);
    }//GEN-LAST:event_menuListarEmpleadosActionPerformed

    private void menuSumatoriaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSumatoriaEmpleadoActionPerformed
        GUISumatoriaSalarios gui = new GUISumatoriaSalarios();
        gui.setVisible(true);
    }//GEN-LAST:event_menuSumatoriaEmpleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem menuActualizarEmpleado;
    private javax.swing.JMenuItem menuActualizarEmpresa;
    private javax.swing.JMenuItem menuAdicionarEmpleado;
    private javax.swing.JMenuItem menuAdicionarEmpresa;
    private javax.swing.JMenuItem menuBuscarEmpleado;
    private javax.swing.JMenuItem menuBuscarEmpresa;
    private javax.swing.JMenuItem menuDesarrolladores;
    private javax.swing.JMenuItem menuElimiarEmpresa;
    private javax.swing.JMenuItem menuEliminarEmpresa;
    private javax.swing.JMenuItem menuListarEmpleados;
    private javax.swing.JMenuItem menuListarEmpresa;
    private javax.swing.JMenuItem menuSumatoriaEmpleado;
    private javax.swing.JMenuItem menuSumatoriaEmpresa;
    // End of variables declaration//GEN-END:variables
}
