/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prototipo1.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author anaso
 */
public class GUIPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIPrincipal.class.getName());

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuAdicionar = new javax.swing.JMenuItem();
        menuBuscar = new javax.swing.JMenuItem();
        menuActualizar = new javax.swing.JMenuItem();
        menuEliminar = new javax.swing.JMenuItem();
        menuListar = new javax.swing.JMenuItem();
        menuSumatoria = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuDesarrolladores = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Principal");

        jMenu2.setText("Inicio");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Empresa");

        menuAdicionar.setText("Adicionar Empresa");
        menuAdicionar.addActionListener(this::menuAdicionarActionPerformed);
        jMenu3.add(menuAdicionar);

        menuBuscar.setText("Buscar Empresa");
        menuBuscar.addActionListener(this::menuBuscarActionPerformed);
        jMenu3.add(menuBuscar);

        menuActualizar.setText("ActualizarEmpresa");
        menuActualizar.addActionListener(this::menuActualizarActionPerformed);
        jMenu3.add(menuActualizar);

        menuEliminar.setText("Eliminar Empresa");
        menuEliminar.addActionListener(this::menuEliminarActionPerformed);
        jMenu3.add(menuEliminar);

        menuListar.setText("Listar Empresa");
        menuListar.addActionListener(this::menuListarActionPerformed);
        jMenu3.add(menuListar);

        menuSumatoria.setText("Sumatoria");
        menuSumatoria.addActionListener(this::menuSumatoriaActionPerformed);
        jMenu3.add(menuSumatoria);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Acerca de");

        menuDesarrolladores.setText("Desarrolladores");
        menuDesarrolladores.addActionListener(this::menuDesarrolladoresActionPerformed);
        jMenu4.add(menuDesarrolladores);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDesarrolladoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDesarrolladoresActionPerformed
        String mensaje = "Desarrolladores: \n\n" + 
                "Paula Daniela Cubillos \n" +
                "Michael Stiven Castaño \n" +
                "Ana Sofia Vergara \n";
        JOptionPane.showInternalMessageDialog(null, mensaje);
    }//GEN-LAST:event_menuDesarrolladoresActionPerformed

    private void menuAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdicionarActionPerformed
        GUIAdicionarEmpresa gui = new GUIAdicionarEmpresa();
        gui.setVisible(true);
    }//GEN-LAST:event_menuAdicionarActionPerformed

    private void menuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarActionPerformed
        GUIBuscarEmpresa gui = new GUIBuscarEmpresa();
        gui.setVisible(true);
    }//GEN-LAST:event_menuBuscarActionPerformed

    private void menuActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActualizarActionPerformed
        GUIActualizarEmpresa gui = new GUIActualizarEmpresa();
        gui.setVisible(true);
    }//GEN-LAST:event_menuActualizarActionPerformed

    private void menuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEliminarActionPerformed
        GUIEliminarEmpresa gui = new GUIEliminarEmpresa();
        gui.setVisible(true);
    }//GEN-LAST:event_menuEliminarActionPerformed

    private void menuListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarActionPerformed
        GUIListarEmpresas gui = new GUIListarEmpresas();
        gui.setVisible(true);
    }//GEN-LAST:event_menuListarActionPerformed

    private void menuSumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSumatoriaActionPerformed
        GUISumatoriaIngresos gui = new GUISumatoriaIngresos();
        gui.setVisible(true);
    }//GEN-LAST:event_menuSumatoriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem menuActualizar;
    private javax.swing.JMenuItem menuAdicionar;
    private javax.swing.JMenuItem menuBuscar;
    private javax.swing.JMenuItem menuDesarrolladores;
    private javax.swing.JMenuItem menuEliminar;
    private javax.swing.JMenuItem menuListar;
    private javax.swing.JMenuItem menuSumatoria;
    // End of variables declaration//GEN-END:variables
}
